apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nextcloud-data-HDD-pvc
  name: nextcloud-data-pvc
  namespace: nextcloud
spec:
  storageClassName: hdd-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
status: {}
